### ISSUE TITLE
Update Lab Source code with latest Azure Bot Service functionality

### ISSUE THREAD

**Issue by mstruys** [Maarten-Work/VBC-ABS-HOL#1]
The Visual Studio 2017 project code has changed since the Azure Bot Service came out of preview. In order to compile properly, changes need to be made to the web.config file (manual action for now). Without those changes, the project does not compile!

**Comment by Maarten-Work** [comment]
Fixed by manually adding the AzureWebJobsStorage key value combination to the web.config file. Not having this key in there results in a run exception when running the bot in its web app.
